server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: config-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:127.0.0.1}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:kaoyan}
    password: ${RABBIT_MQ_PASSWORD:kaoyan123}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Japoos/config.git
          searchPaths: /

management:
  endpoints:
    web:
      exposure:
        include: '*'